### ISSUE TITLE
Launch error : The SUID sandbox helper binary was found, but is not configured correctly (Ubuntu 24.04 LTS)

### ISSUE THREAD

**Issue by obook** [Andaroth/ai-assistant-electron#1]
"The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that chatgpt-electron-linux-x64/chrome-sandbox is owned by root and has mode 4755."

Since 24.04, AppArmor do not allow execution without sandbox, see [
AppArmor user namespace creation restrictions cause many applications to crash with SIGTRAP ](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844)

You could run the appimage with the --no-sandbox-option:

`$ ./chatgpt-electron --no-sandbox`

**Comment by Andaroth** [comment]
Thanks for opening this issue.

I updated `package.json` so it will automatically run the dev mode with `--no-sandbox` option.

In that regard I added more scripts to cover more development setups. 


If you encounter this error while using the build package, please create a specific ArmorRule and send me a feedback.
