### ISSUE TITLE
comment lancer sur windows 11 ?

### ISSUE THREAD

**Issue by DjarallahBrahim** [Andaroth/ai-assistant-electron#3]
Bonjour

après le lancement de 
```
npm i
npm run package
```

j'ai déplacé le dossier en question mais le fichier .app n'est pas éxucutable voir la photo

![image](https://github.com/user-attachments/assets/e6320ffd-5352-4670-b9d3-0d94217e724e)

**Comment by Andaroth** [comment]
Le `.app` n'est pas un build Windows, vous avez une version Linux.
Téléchargez les sources et faites les commandes : 
`npm i`
`npm run package`
Dans l'ordre.
Bon courage.
